ktor {
  deployment {
    port = 8080
    port = ${?KTOR_INNER_PORT}
    host = "0.0.0.0"
  }
  application {
    modules = [
      com.kalashnikovprojects.ufmserver.plugins.KoinKt.configureKoin
      com.kalashnikovprojects.ufmserver.plugins.SerializationKt.configureSerialization
      com.kalashnikovprojects.ufmserver.plugins.DatabaseKt.configureDatabase
      com.kalashnikovprojects.ufmserver.plugins.StatusPagesKt.configureStatusPages
      com.kalashnikovprojects.ufmserver.plugins.RateLimitKt.configureRateLimit
      com.kalashnikovprojects.ufmserver.plugins.SecurityKt.configureSecurity
      com.kalashnikovprojects.ufmserver.plugins.WebsocketsKt.configureWebsockets
      com.kalashnikovprojects.ufmserver.plugins.LoggingKt.configureLogging
      com.kalashnikovprojects.ufmserver.plugins.RoutingKt.configureRouting
    ]
  }
}
jwt {
    domain = "UFM"
    realm = "universal food menu"
    secret = ${JWT_SECRET}
}

db {
    host = "localhost:5435",
    host = ${?POSTGRES_HOST},
    name = ${POSTGRES_DB},
    user = ${POSTGRES_USER},
    password = ${POSTGRES_PASSWORD},
}

server {
    base_url = "http://10.0.2.2:8080" // change to http://localhost:8096 and them to https://ufm.taprams.ru
    base_url = ${?SERVER_HOST}
}