services:
  ufm-server:
    volumes:
      - ufm-static:/var/lib/postgresql/data
    build: .
    ports:
      - "8096:8080"
    environment:
      SERVER_HOST:
        localhost:8096
    env_file:
      - stack.env  # POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
    depends_on:
      ufm-db:
        condition: service_healthy
    restart: unless-stopped

  ufm-db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ufm_db
    env_file:
      - stack.env  # POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    restart: unless-stopped

volumes:
  postgres:
  ufm-static: